### ISSUE TITLE
I got stuck while installing.

### ISSUE THREAD

**Issue by lvlupharshit** [ShivamJoker/RN-Rock-Paper-Scissors#16]
I am a beginner and please don't mind if I am wrong but I can't tun npm install here. Please tell me how can I move forward.

Image
<img width="751" alt="image" src="https://user-images.githubusercontent.com/80972264/167090271-fdf253e7-754b-4b94-8c7a-b4f75662281a.png">

I also tried "npm install react-native-macos" but didn't worked.

**Comment by ShivamJoker** [comment]
You are on windows, you can't run macos. Also use yarn, it should fix the error.

**Comment by lvlupharshit** [comment]
Yarn install worked successfully. But after running I got 

`error ENOENT: no such file or directory, open 'undefined/src/main/AndroidManifest.xml'`

Sorry for disturbing 😅

**Comment by ShivamJoker** [comment]
Please look into stackoverflow, I don't use windows and don't recommend as well.
